-- Module 5: Snowflake - Data Analytics
-- Task 1: Snowflake Setup (Database, Warehouse, Schema)

-- Create Database
CREATE DATABASE IF NOT EXISTS MONEY_TRANSFER_DW;

-- Create Schema
CREATE SCHEMA IF NOT EXISTS MONEY_TRANSFER_DW.ANALYTICS;

-- Create Warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH 
WITH WAREHOUSE_SIZE = 'XSMALL' 
AUTO_SUSPEND = 60 
AUTO_RESUME = TRUE;

-- Select context
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MONEY_TRANSFER_DW;
USE SCHEMA ANALYTICS;
